package ru.macrobit.abonnews;

public class Values {
    public static final String URL = "http://abon-news.ru/";
    public static final String GET_POST = URL + "wp-json/posts?filter[posts_per_page]=-1";
    public static final String AUTHORIZATION = URL + "wp-login.php";
    public static final String POSTS = URL + "wp-json/posts/";
    public static final String MEDIA_ADD = URL + "wp-json/media";
    public static final String MEDIA = URL + "wp-json/media?filter[posts_per_page]=-1";
    public static final String COMMENTS = "/comments";
    public static final String PUSH = URL + "/push";
    public static final String MY_COMMENTS = URL + "/wp-json/comments/my";
    public static final String SEARCH = URL + "wp-json/postsnew?filter[s]=";
    public static final String GET_PAGE_POSTS = URL + "/wp-json/postsnew?filter[posts_per_page]=10&page=";
    public static final String REGISTRY = URL + "wp-login.php?action=register";
    public static final String PREF = "Abon news preferences";
    public static final String COOKIES = "cookies";
    public static final String PROFILE = URL + "wp-json/users/me";
    public static final String ADS = URL +  "/wp-json/ads";
    public static final int REQUEST_ULOGIN = 1;
    public static final String TOKEN = "token";
    public static final String EMAIL = "email";
    public static final String ULOGIN = URL + "?ulogin=token&backurl=http://abon-news.ru/wp-login.php?loggedout=true";
//    public static final String SOC_AUTORIZATION = URL + "?ulogin=token&backurl=http://abon-news.ru/wp-login.php";
    public static final String SOC_AUTORIZATION = "http://abon-news.ru/?ulogin=token&backurl=http%3A%2F%2Fabon-news.ru%2Fwp-login.php%3Fredirect_to%3Dhttp%253A%252F%252Fabon-news.ru%252Fwp-admin%252F%26reauth%3D1";
    public static final String DETAIL_TAG = "detail";
    public static final String AUTHORIZATION_TAG = "authorization";
    public static final String NEWS_TAG = "news";
    public static final String PROFILE_TAG = "profile";
    public static final String ADD_TAG = "add";
    public static final String ABOUT_TAG = "about";
    public static final String REGISTRATION_TAG = "registry";
    public static final String MY_COMMENTS_TAG = "my comments";
    public static final String TAG = "tag";
    public static final String FULL_NEWS = "full";
    public static final String FACEBOOK = "http://www.facebook.com/sharer/sharer.php?u=";
    public static final String VK = "https://vk.com/share.php?url=";
    public static final String OK = "http://www.odnoklassniki.ru/dk?st.cmd=addShare&st.s=1&st._surl=";
    public static final String TWITTER = "http://twitter.com/share?text=";
    public static final String ABON_LOGO = "http://abon-news.ru/wp-content/themes/abon/images/logo.png";
    public static final String ADS_PREF = "ads";
    public static final int MEDIA_RESULT = 121;
    public static boolean isDisplayHomeEnabled;
}
